### ISSUE TITLE
Any plans on add socket.io?

### ISSUE THREAD

**Issue by ghost** [brunoscopelliti/poker-holdem-engine#1]
Hi,
do you plan to use socket.io to support WebSockets instead of POST Requests? Or are you interested in a Pull Request making this happen?

**Comment by brunoscopelliti** [comment]
Hi,

thank you for your interest in poker-holdm-engine.

Currently I am using request's POST to send the gamestate object to the bot which are playing the tournament, and receving back players' bets. This is the only network request I've to do.

What would be the advantages of using socket.io?
I understand socket.io would be greatly faster... but this is not appealing for me, because the game is already so fast, that I had to add the possibility to slow down it a little.

Another cons of using socket.io is that it would require to use socket.io also on the clients (the bots implementing poker strategy); but the clients shouldn't be forced to use node.js as language... indeed I'm currently using this library for [bot poker](https://bot-poker.herokuapp.com/about) and the bots can be written in javascript, php, python, ruby (probably even more in the future).
Even if propably for these languages do exist something like socket.io I am not expert enough to use it.
